### ISSUE TITLE
edit ui 

### ISSUE THREAD

**Issue by rowanibrahem** [AHMED739268/chatapp#2]
![Screenshot_1727888124 - mohammed eid](https://github.com/user-attachments/assets/7f4f66ff-36f3-4cba-9189-e6d6b2251a3e)

اعمل ui زي دا لو سمحت

**Comment by AHMED739268** [comment]
انا عدلت الui فعلا  ورفعته لاكن لسا هعدل اسماء الملفات جوا الcore
